/*
 * Copyright 2016 Workday, Inc.
 *
 * This software is available under the MIT license.
 * Please see the LICENSE.txt file in this project.
 */

package com.workday.autoparse.json.parser;

import java.util.Set;

/**
 * A holder for a map from discrimination value to {@link JsonObjectParser} instance. The
 * implementation of this class is generated by Autoparse.
 *
 * @author nathan.taylor
 * @since 2014-10-09
 */
public interface JsonObjectParserTable {

    JsonObjectParser<?> get(String discriminationValue);

    Set<String> keySet();
}
